== Creating random seeds

While implementing the http://jenetics.io/[Jenetics] library, I faced the problem of creating seed values for the Random engines I used. The usual way for doing this, is to take the current time stamp.

.Using timestamp as seed value
[source,java]
--------------
public static long seed() {
    return System.nanoTime();
}
--------------

To test the statistical quality for this kind of seed values, I treated it as *special* random engine and applied the http://www.phy.duke.edu/~rgb/General/dieharder.php[dieharder] test suite to it. As you might expect, the quality of this random engine was    disastrous. It didn't pass a single *dieharder* test:

.Dieharder result for timestamp seed
[source,bash]
-----------------
#=============================================================================#
# Summary: PASSED=0, WEAK=0, FAILED=114                                       #
#          233,969.062 MB of random data created with 58.038 MB/sec           #
#=============================================================================#
-----------------

After this failure, I was searching for a different entropy source. For Linux system you probably want to choose `/dev/random` or `/dev/urandom` as source for your seeds. But this approach is not portable, which was a prerequisite for the Jenetics library. Since the hash code of an Object is available for every operating system, I tried to combine two `Object` hash codes to one seed value:

.Using `Object.hashCode()` as seed value
[source,java]
-------------
public static long seed() {
    return ((long)(new Object().hashCode()) << 32) |
        new Object().hashCode();
}
-------------

Running the same *dieharder* tests, lead to the following result:

.Dieharder result for `Object.hashCode()` seed
[source,bash]
-----------------
#=============================================================================#
# Summary: PASSED=28, WEAK=0, FAILED=86                                       #
#          234,759.406 MB of random data created with 43.149 MB/sec           #
#=============================================================================#
-----------------
