/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jenetics_util_IndexStream */

#ifndef _Included_org_jenetics_util_IndexStream
#define _Included_org_jenetics_util_IndexStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jenetics_util_IndexStream
 * Method:    next
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_jenetics_util_IndexStream_next
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
