/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jenetics.example.image;

import java.text.NumberFormat;
import java.time.Duration;

import org.jenetics.engine.EvolutionResult;


public class EvolutionResultPanel extends javax.swing.JPanel {

	private static final NumberFormat _fitnessFormat = NumberFormat.getNumberInstance();
	private static final NumberFormat _durationMillisFormat = NumberFormat.getNumberInstance();

	/**
	 * Creates new form EvolutionResultPanel
	 */
	public EvolutionResultPanel() {
		initComponents();

		_fitnessFormat.setMaximumIntegerDigits(1);
		_fitnessFormat.setMinimumIntegerDigits(1);
		_fitnessFormat.setMinimumFractionDigits(4);
		_fitnessFormat.setMaximumFractionDigits(4);
		
		_durationMillisFormat.setMaximumIntegerDigits(3);
		_durationMillisFormat.setMinimumIntegerDigits(3);
		_durationMillisFormat.setMinimumFractionDigits(0);
		_durationMillisFormat.setMaximumFractionDigits(0);
	}

	void update(final EvolutionResult<?, Double> result) {
		_generationTextField.setText(Long.toString(result.getGeneration()));
		_bestFitnessTextField.setText(_fitnessFormat.format(result.getBestFitness()));
		_worstFitnessTextField.setText(_fitnessFormat.format(result.getWorstFitness()));
		_evaluationTimeTextField.setText(format(result.getDurations().getEvaluationDuration()));
		_evolutionTimeTextField.setText(format(result.getDurations().getEvolveDuration()));
	}

	private static String format(final Duration duration) {
		return String.format(
			"%d.%s s",
			duration.getSeconds(), 
			_durationMillisFormat.format(duration.getNano()/1_000_000)
		);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		_generationLabel = new javax.swing.JLabel();
		_generationTextField = new javax.swing.JTextField();
		_bestFitnessLabel = new javax.swing.JLabel();
		_bestFitnessTextField = new javax.swing.JTextField();
		_worstFitnessLabel = new javax.swing.JLabel();
		_worstFitnessTextField = new javax.swing.JTextField();
		_evaluationTimeLabel = new javax.swing.JLabel();
		_evaluationTimeTextField = new javax.swing.JTextField();
		_evolutionTimeLabel = new javax.swing.JLabel();
		_evolutionTimeTextField = new javax.swing.JTextField();

		setLayout(new java.awt.GridBagLayout());

		_generationLabel.setText("Generation:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
		add(_generationLabel, gridBagConstraints);

		_generationTextField.setEditable(false);
		_generationTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				_generationTextFieldActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
		add(_generationTextField, gridBagConstraints);

		_bestFitnessLabel.setText("Best fitness:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
		add(_bestFitnessLabel, gridBagConstraints);

		_bestFitnessTextField.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
		add(_bestFitnessTextField, gridBagConstraints);

		_worstFitnessLabel.setText("Worst fitness:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
		add(_worstFitnessLabel, gridBagConstraints);

		_worstFitnessTextField.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
		add(_worstFitnessTextField, gridBagConstraints);

		_evaluationTimeLabel.setText("Evaluation time:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
		add(_evaluationTimeLabel, gridBagConstraints);

		_evaluationTimeTextField.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
		add(_evaluationTimeTextField, gridBagConstraints);

		_evolutionTimeLabel.setText("Evolution time:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
		add(_evolutionTimeLabel, gridBagConstraints);

		_evolutionTimeTextField.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
		add(_evolutionTimeTextField, gridBagConstraints);
	}// </editor-fold>//GEN-END:initComponents

	private void _generationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__generationTextFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event__generationTextFieldActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel _bestFitnessLabel;
	private javax.swing.JTextField _bestFitnessTextField;
	private javax.swing.JLabel _evaluationTimeLabel;
	private javax.swing.JTextField _evaluationTimeTextField;
	private javax.swing.JLabel _evolutionTimeLabel;
	private javax.swing.JTextField _evolutionTimeTextField;
	private javax.swing.JLabel _generationLabel;
	private javax.swing.JTextField _generationTextField;
	private javax.swing.JLabel _worstFitnessLabel;
	private javax.swing.JTextField _worstFitnessTextField;
	// End of variables declaration//GEN-END:variables
}
